### ISSUE TITLE
[DTM-16] uses GG Sans instead of whitney. 

### ISSUE THREAD

**Issue by apprname** [XYZenix/XYZenixThemes#139]
title is self-explanatory
can be fixed with this css https://raw.githubusercontent.com/Overimagine1/old-discord-font/main/source.css

**Comment by XYZenix** [comment]
since i guess i wasn't clear last time, i'm not adding whitney back to DTM-16 only for it to use font files hosted from elsewhere, first because i doubt the person rehosting the files paid for the font or has rights to rehost it (regardless of whether anyone is going to do anything about it), and second i want my theme to work without client mods. if you use client mods then you can just apply an 'old discord font' theme on top and have it work, or alternatively install whitney as a system font and use that

discord's CORS means it's essentially impossible to have external fonts work in themes without a client mod/extension patch - the only other option is (if that even still works) to store the entire font as a base64 url in the theme, which is the exact same thing as rehosting the font which i'm not going to risk doing
