### ISSUE TITLE
[DTM-16] Green background while listening spotify

### ISSUE THREAD

**Issue by DanGamingBlue** [XYZenix/XYZenixThemes#60]
![image](https://user-images.githubusercontent.com/75522691/191918419-49286c75-902d-4363-b9bf-87b7c21aae80.png)
Is that possible to make green background while listening spotify like few years ago?

**Comment by XYZenix** [comment]
it works on the old profile ui just get good and don't be in the group of 90% of people who have the new profile ui 👍

jokes aside yes but either way it will only work on chrome n stuff because discord's client uses a fossil version of electron which also uses a fossil version of chromium which doesn't support the `:has()` css selector so implementing this on the new profile ui is not going to be a priority (also it'll only work on the user popout, not the full profile, because there's no selector on the full profile (technically there is but only in the activity tab so that wont work))

**Comment by DanGamingBlue** [comment]
Okay, thanks for reply

**Comment by XYZenix** [comment]
i'm closing this, i redid user popouts and that includes custom header backgrounds for various activities, including spotify. of course, this requires using web discord as this uses `:has()`, which discord's client doesn't support due to using an old version of electron, and thus chromium
