### ISSUE TITLE
DTM-08 does not properly display the new Nitro color gradients, reducing them to only a thin border

### ISSUE THREAD

**Issue by dankxen0n** [XYZenix/XYZenixThemes#73]
without DTM-08 on: 
![image](https://user-images.githubusercontent.com/71655697/211221520-04a8d55d-1b60-405b-a597-d4db3320f9a0.png)

with DTM-08 on:
![image](https://user-images.githubusercontent.com/71655697/211221608-515c5256-8995-478c-8a09-d1ab022d4307.png)

**Comment by XYZenix** [comment]
this is intentional as i did not want to completely hide profile themes but couldn't think of a way to incorporate them into DTM-08 at the time
this may be changed later, in which case i may reference this issue in a future commit where i do change the styling of user popouts

**Comment by K4sum1** [comment]
What's the first theme? Could look at what it does?

**Comment by dankxen0n** [comment]
> What's the first theme? Could look at what it does?

skeuocord

**Comment by XYZenix** [comment]
well since this has been brought up again, i reworked profiles in DTM-08 V2 to keep the gradient fully visible:
![image](https://user-images.githubusercontent.com/51988432/228981519-3ca2adc4-7fdb-4ca5-a924-203912c71b46.png)
i will eventually replace the current version of DTM-08 with V2 eventually once i finish everything, but it works well enough if you use dark mode if you want to try it ([link](https://github.com/XYZenix/XYZenixThemes/tree/master/DTM-08-V2))

**Comment by K4sum1** [comment]
I'll try it, lemme know when v2 gets merged into stable.

**Comment by XYZenix** [comment]
i think it's visually distinct enough that you'd notice, but i'll try and mention it somewhere

**Comment by K4sum1** [comment]
I mean I'm switching to v2 right now, just let me know when it's stable so I can switch back to stable.
