### ISSUE TITLE
[DTM-08 v2] Server list suggestion(?)

### ISSUE THREAD

**Issue by K4sum1** [XYZenix/XYZenixThemes#78]
It's kinda hard to tell if a server is selected going by the list since it doesn't expand when clicked. like adding a color as a background behind the server icon could be used to better indicate a selected server. Not that big of a deal since I can read, but it seems odd to have only the expanding dot.

Also if the server list is squares with rounded corners, everything else (members mostly) should be as well.

**Comment by XYZenix** [comment]
i originally opted in to make server and user pfps rounded square, however that caused me a dozen problems involving status icons, and later realized that even if i did fix that, another problem i CAN'T fix is avatar decorations, which will always look weird because they're always designed with circle pfps in mind.

server icons i decided to make square and keep square anyway because i thought it'd look better on the server list. i'll experiment with different styles and see what works.

**Comment by XYZenix** [comment]
![image](https://user-images.githubusercontent.com/51988432/228986810-38bf9694-1b06-400d-8a8a-c4efbe23b45b.png)
opinions on this?

(also would be nice if we continued this conversation in the discord server)

**Comment by K4sum1** [comment]
Yeah, that looks pretty nice. Will join Discord.
