### ISSUE TITLE
Profile badge location could be adjusted...

### ISSUE THREAD

**Issue by teenecks** [XYZenix/XYZenixThemes#84]
![image](https://github.com/XYZenix/XYZenixThemes/assets/118153405/cca2f554-631c-417d-901e-fe32f6e520c9)

Please just move dat jawn...

**Comment by XYZenix** [comment]
all that stuff uses absolute positioning meaning i would have to manually adjust this in at least 15 different ways based on the badge count so not really an option. and i especially can't move it to the right of the username because i have no way of knowing how long the username/status/etc. is so i can't adjust the badges accordingly

**Comment by teenecks** [comment]
aw man... that's dumb unfortunate...

**Comment by teenecks** [comment]
![image](https://github.com/XYZenix/XYZenixThemes/assets/118153405/bcf64d6e-876c-4064-ab6c-ee45392a5dc5)
What about like this though.... discord names cant be THAT long and pronouns could be made a little smaller or something idk, anywhere but the top left dawg..

**Comment by teenecks** [comment]
nvm, just realized that's where the status goes... v-v

**Comment by XYZenix** [comment]
the profile ui in DTM-16 has had to be recreated dozens of times and even though each remake gets a bit better, with the structure of the current profile ui, it's gonna take a LOT of `:has()` statements to make it look good enough. the reason badges aren't grouped with the rest is because layout-wise they're completely separate and use absolute positioning. there isn't really a good way to make everything centered, at the end i'd have no way to account for stuff like the username/nickname/status being long enough to create a newline so in such situations i'd have to cut off text and i don't think that's a good solution.

the reason i moved pronouns to the right is due to them forcing the username & status to clip through the badges on profiles that don't have a banner set, and the reason i don't just resize the banner is because ideally i shouldn't, and the whole banner is an SVG which is annoying to work with; the border between the avatar and the banner is a part of that SVG and it's extremely annoying to try and get it positioned properly and i can't think of any good way around it

**Comment by teenecks** [comment]
i feel you, my bad aint mean 2 be annoying, them badges was just bothering me but i understand u cant do much about it. just a matter of time till you figure something out
